baseURL = 'https://tofudreams.com/'
languageCode = 'en-us'
title = 'Tofu Dreams'
description = "A blog about tofu and dreams"

theme = 'bean'

summaryLength = 10
paginate = 6

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

[params]
  logo = "logo.png"
  icon = "favicon.png"
  name = "Tofu Dreams"
  description = "A blog about tofu and dreams"


